version: '3'
services:
  db:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "maugami"
      POSTGRES_PASSWORD: "maugami"
      POSTGRES_DB: "testDB"
    ports:
       - "5432:5432"
  web:
    build: .
    ports:
    - "8080:8080"

